<a href="https://colab.research.google.com/github/lasatamanandhar/ComputationalMath/blob/main/Workshop6_Math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Name: Lasata Manandhar

Student Id: 2603723

Part 1

In [1]:
#Problem 1: Create a 2D ndarray of type Integer and see its properties.

import numpy as np

X = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

print(X)
print(X.shape)
print(X.dtype)
print(X.ndim)

#Displaying properties
print("Array:\n",X)
print("Shape of array                :", X.shape)
print("Data type  of array           :", X.dtype)
print("Number of dimensions of array :", X.ndim)
print("Sizeof array (total elements) :", X.size)
print("Item size (bytes)             :", X.itemsize)
print("Total bytes                   :", X.nbytes)
print("Memory layout information     :",X.flags)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
int64
2
Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape of array                : (3, 3)
Data type  of array           : int64
Number of dimensions of array : 2
Sizeof array (total elements) : 9
Item size (bytes)             : 8
Total bytes                   : 72
Memory layout information     :   C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [2]:
#Problem 2: Create a 2D ndarray (matrix) of shape (4,5) with all elements equal to 3.0 and print the matrix.

X = np.ones((4,5)) * 3.0
print(X)

print("Shape of array:", X.shape)
print("Data type  of array:", X.dtype)
print("Number of dimensions of array:", X.ndim)

[[3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]]
Shape of array: (4, 5)
Data type  of array: float64
Number of dimensions of array: 2


In [3]:
#Problem 3: The other way to create the same matrix as above.
X = np.full((4,5), 3.0)
print(X)

print("Shape of array:", X.shape)
print("Data type  of array:", X.dtype)
print("Number of dimensions of array:", X.ndim)

[[3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]]
Shape of array: (4, 5)
Data type  of array: float64
Number of dimensions of array: 2


In [4]:
#Problem 4: a matrix of shape (3,3) whose elements are given by aij = 1/2 |𝑖 − 3𝑗|.

X = np.zeros((3,3))

for i in range(3):
    for j in range(3):
        X[i][j] = 0.5 * abs((i+1) - 3*(j+1))

print(X)
print("Shape     :",X.shape)
print("Data type :",X.dtype)

[[1.  2.5 4. ]
 [0.5 2.  3.5]
 [0.  1.5 3. ]]
Shape     : (3, 3)
Data type : float64


In [5]:
#Problem 5: Construct a diagonal matrix of shape (4,4) whose diagonal elements are [1,2,3,4]

A = np.diag([1,2,3,4])
print(A)

print("Shape     :",A.shape)
print("Data type :",A.dtype)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
Shape     : (4, 4)
Data type : int64


In [6]:
"""Probelm 6: Construct a matrix of shape (4,5) with whatever elements, and then slice it to obtain
 a matrix of shape (3,3) that contains only upper-left portion of the original matrix"""

A = np.arange(20).reshape(4,5)
print("Original array:",A)

B = A[:3, :3]
print("New array:",B)

Original array: [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
New array: [[ 0  1  2]
 [ 5  6  7]
 [10 11 12]]


Part 2

In [22]:
#Problem 1: Create matrices A of order 3*3 and B of order 3*2. Add them together.
#What do you observe? Give explanation behind it.

import numpy as np

A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

B = np.array([[1,1,6],
              [2,2,8],
              [3,3,5]]) # Changed B to be a 3x2 matrix

print (A + B)

[[ 2  3  9]
 [ 6  7 14]
 [10 11 14]]


The matrices cannot be added as both the matrices has different dimensions.

In [12]:
#Problem 2: Given a matrix and a vector, write a Python function that performs Matrix-Vector product.
#Check your result with NumPy built-in function to perform Matrix-Vector/Matrix-Matrix product.

import numpy as np
def dot_product(vec1, vec2):

    vec1 = vec1.flatten()
    vec2 = vec2.flatten()
    return np.sum(np.multiply(vec1, vec2))

def matrix_vector_product(mat, vec):
    m, n = mat.shape
    p, q = vec.shape

    assert n == p, "The matrix and vector are not compatible for multiplication!"

    result = np.zeros((m, q), dtype=float)

    for i in range(m):
        result[i] = dot_product(mat[i, :], vec)

    return result

mat1 = np.full((3, 3), 3, dtype=int)
vec1 = np.full((3, 1), 2, dtype=int)

print("Matrix = \n", mat1)
print("Vector = \n", vec1)

result1 = matrix_vector_product(mat1, vec1)
print("Result1 (Manual) = \n", result1)

result2 = mat1 @ vec1
print("Result2 (NumPy @) = \n", result2)

Matrix = 
 [[3 3 3]
 [3 3 3]
 [3 3 3]]
Vector = 
 [[2]
 [2]
 [2]]
Result1 (Manual) = 
 [[18.]
 [18.]
 [18.]]
Result2 (NumPy @) = 
 [[18]
 [18]
 [18]]


In [13]:
#Problem 3: Given two compatible matrices, write a Python function that performs Matrix-Matrix product.
#Check your result with NumPy built-in function to perform Matrix-Vector/Matrix-Matrix product.

import numpy as np

def dot_product(vec1, vec2):
    vec1 = vec1.flatten()
    vec2 = vec2.flatten()
    return np.sum(np.multiply(vec1, vec2))

def matrix_matrix_product(matA, matB):
    m, n = matA.shape
    p, q = matB.shape

    assert n == p, "Matrices are not compatible for multiplication!"

    result = np.zeros((m, q), dtype=float)

    for i in range(m):
        for j in range(q):
            result[i, j] = dot_product(matA[i, :], matB[:, j])

    return result

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

res_manual = matrix_matrix_product(A, B)

res_numpy = A @ B

print("Manual Result:\n", res_manual)
print("NumPy Result:\n", res_numpy)

Manual Result:
 [[19. 22.]
 [43. 50.]]
NumPy Result:
 [[19 22]
 [43 50]]


In [14]:
#Problem 4: : Given a matrix, write a Python function that checks if it is a symmetric matrix.

def is_symmetric(X):
    X = np.array(X)
    return np.array_equal(X, X.T)


X = [[9,3,6],
     [2,8,6],
     [3,5,9]]

print(is_symmetric(X))

False
